#!/bin/sh
python3 sac.py --exp_name youbot_manip --ENV youBot_arm --OBSERVATION_LOW --ARM --REWARD_DENSE --RPA 1 --HIDDEN_SIZE 256 --BATCH_SIZE 128 -lr 0.0001 -steps 50000 --TEST_INTERVAL 2000 --DEMONSTRATIONS 'youbot_arm1' --UPDATE_START 0 --PRIORITIZE_REPLAY --BEHAVIOR_CLONING
